version: 2
updates:
  - package-ecosystem: npm # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "npm"
    groups:
      prod-updates:
        dependency-type: production
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: development
        update-types:
          - "major"
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: ".github/workflows" # Location of workflow files
    labels:
      - "dependencies"
      - "github-actions"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "action (deps)"
    groups:
      patch-minor-updates:
        update-types:
          - "patch"
          - "minor"
